---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssh
  annotations:
    tekton.dev/git-0: {{ .Values.gitHost.name }}
type: kubernetes.io/ssh-auth
{{- if .Release.IsInstall }}
data:
  ssh-privatekey: {{ genPrivateKey "rsa" | b64enc }}
  {{- if .Values.gitHost.knownHostsString }}
  known_hosts: {{ .Values.gitHost.knownHostsString | b64enc }}
  {{- end }}
{{- else }}
data: {{ index (lookup "v1" "Secret" .Release.Namespace ( printf "%s-ssh" .Release.Name )) "data" | toJson }}
{{- end }}
