---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssh
  annotations:
    tekton.dev/git-0: {{ .Values.gitHost.name }}
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ genPrivateKey "rsa" | b64enc }}
  {{- if .Values.gitHost.knownHostsString }}
  known_hosts: {{ .Values.gitHost.knownHostsString | b64enc }}
  {{- end }}
