---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webhook
data:
{{- if .Release.IsInstall }}
  value: {{ randAscii 12 | b64enc }}
{{- else }}
  value: {{ (lookup "v1" "Secret" .Release.Namespace ( print .Release.Name "-webhook" )).data.value }}
{{- end }}
